#!/bin/bash
# Engram Memory Wrapper for OpenClaw
# Usage: engram-save "title" "content" [--type TYPE] [--project PROJECT] [--topic TOPIC]

set -e

COMMAND="$1"
shift

case "$COMMAND" in
  save)
    TITLE="$1"
    CONTENT="$2"
    shift 2
    
    TYPE="discovery"
    PROJECT="examen_grado"
    TOPIC=""
    
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --type)
          TYPE="$2"
          shift 2
          ;;
        --project)
          PROJECT="$2"
          shift 2
          ;;
        --topic)
          TOPIC="$2"
          shift 2
          ;;
        *)
          shift
          ;;
      esac
    done
    
    if [ -z "$TOPIC" ]; then
      engram save "$TITLE" "$CONTENT" --type "$TYPE" --project "$PROJECT"
    else
      engram save "$TITLE" "$CONTENT" --type "$TYPE" --project "$PROJECT" --topic "$TOPIC"
    fi
    ;;
    
  search)
    QUERY="$1"
    shift
    
    TYPE=""
    PROJECT="examen_grado"
    
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --type)
          TYPE="$2"
          shift 2
          ;;
        --project)
          PROJECT="$2"
          shift 2
          ;;
        *)
          shift
          ;;
      esac
    done
    
    if [ -n "$TYPE" ]; then
      engram search "$QUERY" --type "$TYPE" --project "$PROJECT"
    else
      engram search "$QUERY" --project "$PROJECT"
    fi
    ;;
    
  context)
    PROJECT="${1:-examen_grado}"
    engram context "$PROJECT"
    ;;
    
  timeline)
    ID="$1"
    engram timeline "$ID"
    ;;
    
  stats)
    engram stats
    ;;
    
  session-start)
    engram session_start
    ;;
    
  session-end)
    engram session_end
    ;;
    
  *)
    echo "Usage: $0 <command> [args]"
    echo ""
    echo "Commands:"
    echo "  save <title> <content> [--type TYPE] [--project PROJECT] [--topic TOPIC]"
    echo "  search <query> [--type TYPE] [--project PROJECT]"
    echo "  context [project]"
    echo "  timeline <id>"
    echo "  stats"
    echo "  session-start"
    echo "  session-end"
    exit 1
    ;;
esac
